// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiIqm34TSZzv2TneypttwG2nLvgS-tZM0',
    appId: '1:484370225906:web:ac53b92381409a17ff0e6b',
    messagingSenderId: '484370225906',
    projectId: 'lity-link-app',
    authDomain: 'lity-link-app.firebaseapp.com',
    storageBucket: 'lity-link-app.firebasestorage.app',
    measurementId: 'G-SZLSYG4DV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG4c-MVXb0C7quo9dRGqkWyujvM0N-Jy4',
    appId: '1:484370225906:android:285df3268922af4dff0e6b',
    messagingSenderId: '484370225906',
    projectId: 'lity-link-app',
    storageBucket: 'lity-link-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkt3ORjW4kZDpsXI0WJVJ0-z3csFaonBA',
    appId: '1:484370225906:ios:1dd65b83450ee8d6ff0e6b',
    messagingSenderId: '484370225906',
    projectId: 'lity-link-app',
    storageBucket: 'lity-link-app.firebasestorage.app',
    iosBundleId: 'com.example.maincitylink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkt3ORjW4kZDpsXI0WJVJ0-z3csFaonBA',
    appId: '1:484370225906:ios:1dd65b83450ee8d6ff0e6b',
    messagingSenderId: '484370225906',
    projectId: 'lity-link-app',
    storageBucket: 'lity-link-app.firebasestorage.app',
    iosBundleId: 'com.example.maincitylink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiIqm34TSZzv2TneypttwG2nLvgS-tZM0',
    appId: '1:484370225906:web:a6a4ba7dd61c3f00ff0e6b',
    messagingSenderId: '484370225906',
    projectId: 'lity-link-app',
    authDomain: 'lity-link-app.firebaseapp.com',
    storageBucket: 'lity-link-app.firebasestorage.app',
    measurementId: 'G-QBQ0DT3QMJ',
  );
}
